env:
  matrix:
  - TOMCAT_VERSION=8.0.52 TOMCAT_JAVA_VERSION=jre8 TOMCAT_BASE= LUCEE_VERSION=5.2 LUCEE_SERVER= LUCEE_VARIANT=
  - TOMCAT_VERSION=8.0.52 TOMCAT_JAVA_VERSION=jre8 TOMCAT_BASE= LUCEE_VERSION=5.2 LUCEE_SERVER= LUCEE_VARIANT=-light
  - TOMCAT_VERSION=8.0.52 TOMCAT_JAVA_VERSION=jre8 TOMCAT_BASE=-alpine LUCEE_VERSION=5.2 LUCEE_SERVER= LUCEE_VARIANT=
  - TOMCAT_VERSION=8.0.52 TOMCAT_JAVA_VERSION=jre8 TOMCAT_BASE=-alpine LUCEE_VERSION=5.2 LUCEE_SERVER= LUCEE_VARIANT=-light
langauge: generic
script:
- docker pull docker.io/library/tomcat:$TOMCAT_VERSION-$TOMCAT_JAVA_VERSION$TOMCAT_BASE
- echo "lucee/lucee:$LUCEE_VERSION$LUCEE_SERVER-tomcat$TOMCAT_VERSION-$TOMCAT_JAVA_VERSION$TOMCAT_BASE"
services:
- docker
sudo: required
