env:
  matrix:
  - TOMCAT_VERSION=8.0 TOMCAT_JAVA_VERSION=jre8 TOMCAT_BASE= LUCEE_VERSION=4.5.5.015,5.2.7.62,5.3.0.86-BETA LUCEE_SERVER=,-nginx LUCEE_VARIANTS=,-light
  - TOMCAT_VERSION=8.0 TOMCAT_JAVA_VERSION=jre8 TOMCAT_BASE=-alpine LUCEE_VERSION=4.5.5.015,5.2.7.62,5.3.0.86-BETA LUCEE_SERVER=,-nginx LUCEE_VARIANTS=,-light
  - TOMCAT_VERSION=8.5 TOMCAT_JAVA_VERSION=jre8 TOMCAT_BASE= LUCEE_VERSION=4.5.5.015,5.2.7.62,5.3.0.86-BETA LUCEE_SERVER=,-nginx LUCEE_VARIANTS=,-light
  - TOMCAT_VERSION=8.5 TOMCAT_JAVA_VERSION=jre8 TOMCAT_BASE=-alpine LUCEE_VERSION=4.5.5.015,5.2.7.62,5.3.0.86-BETA LUCEE_SERVER=,-nginx LUCEE_VARIANTS=,-light
  - TOMCAT_VERSION=8.5 TOMCAT_JAVA_VERSION=jre9 TOMCAT_BASE= LUCEE_VERSION=4.5.5.015,5.2.7.62,5.3.0.86-BETA LUCEE_SERVER=,-nginx LUCEE_VARIANTS=,-light
  - TOMCAT_VERSION=8.5 TOMCAT_JAVA_VERSION=jre10 TOMCAT_BASE= LUCEE_VERSION=4.5.5.015,5.2.7.62,5.3.0.86-BETA LUCEE_SERVER=,-nginx LUCEE_VARIANTS=,-light
  - TOMCAT_VERSION=9.0 TOMCAT_JAVA_VERSION=jre8 TOMCAT_BASE= LUCEE_VERSION=4.5.5.015,5.2.7.62,5.3.0.86-BETA LUCEE_SERVER=,-nginx LUCEE_VARIANTS=,-light
  - TOMCAT_VERSION=9.0 TOMCAT_JAVA_VERSION=jre8 TOMCAT_BASE=-alpine LUCEE_VERSION=4.5.5.015,5.2.7.62,5.3.0.86-BETA LUCEE_SERVER=,-nginx LUCEE_VARIANTS=,-light
  - TOMCAT_VERSION=9.0 TOMCAT_JAVA_VERSION=jre9 TOMCAT_BASE= LUCEE_VERSION=4.5.5.015,5.2.7.62,5.3.0.86-BETA LUCEE_SERVER=,-nginx LUCEE_VARIANTS=,-light
  - TOMCAT_VERSION=9.0 TOMCAT_JAVA_VERSION=jre10 TOMCAT_BASE= LUCEE_VERSION=4.5.5.015,5.2.7.62,5.3.0.86-BETA LUCEE_SERVER=,-nginx LUCEE_VARIANTS=,-light
langauge: generic
script:
- python3 build-images.py
services:
- docker
sudo: required
