env:
  matrix:
  - TOMCAT_VERSION=8.0.52 TOMCAT_JAVA_VERSION=jre8 TOMCAT_BASE= LUCEE_VERSION=4.5.5.015,5.3.0.86-BETA,5.2.7.62 LUCEE_SERVER=,-nginx LUCEE_VARIANTS=,-light
  - TOMCAT_VERSION=8.0.52 TOMCAT_JAVA_VERSION=jre8 TOMCAT_BASE=-alpine LUCEE_VERSION=4.5.5.015,5.3.0.86-BETA,5.2.7.62 LUCEE_SERVER=,-nginx LUCEE_VARIANTS=,-light
  - TOMCAT_VERSION=8.5.31 TOMCAT_JAVA_VERSION=jre8 TOMCAT_BASE= LUCEE_VERSION=4.5.5.015,5.3.0.86-BETA,5.2.7.62 LUCEE_SERVER=,-nginx LUCEE_VARIANTS=,-light
  - TOMCAT_VERSION=8.5.31 TOMCAT_JAVA_VERSION=jre8 TOMCAT_BASE=-alpine LUCEE_VERSION=4.5.5.015,5.3.0.86-BETA,5.2.7.62 LUCEE_SERVER=,-nginx LUCEE_VARIANTS=,-light
  - TOMCAT_VERSION=8.5.31 TOMCAT_JAVA_VERSION=jre9 TOMCAT_BASE= LUCEE_VERSION=4.5.5.015,5.3.0.86-BETA,5.2.7.62 LUCEE_SERVER=,-nginx LUCEE_VARIANTS=,-light
  - TOMCAT_VERSION=8.5.31 TOMCAT_JAVA_VERSION=jre10 TOMCAT_BASE= LUCEE_VERSION=4.5.5.015,5.3.0.86-BETA,5.2.7.62 LUCEE_SERVER=,-nginx LUCEE_VARIANTS=,-light
  - TOMCAT_VERSION=9.0.8 TOMCAT_JAVA_VERSION=jre8 TOMCAT_BASE= LUCEE_VERSION=4.5.5.015,5.3.0.86-BETA,5.2.7.62 LUCEE_SERVER=,-nginx LUCEE_VARIANTS=,-light
  - TOMCAT_VERSION=9.0.8 TOMCAT_JAVA_VERSION=jre8 TOMCAT_BASE=-alpine LUCEE_VERSION=4.5.5.015,5.3.0.86-BETA,5.2.7.62 LUCEE_SERVER=,-nginx LUCEE_VARIANTS=,-light
  - TOMCAT_VERSION=9.0.8 TOMCAT_JAVA_VERSION=jre9 TOMCAT_BASE= LUCEE_VERSION=4.5.5.015,5.3.0.86-BETA,5.2.7.62 LUCEE_SERVER=,-nginx LUCEE_VARIANTS=,-light
  - TOMCAT_VERSION=9.0.8 TOMCAT_JAVA_VERSION=jre10 TOMCAT_BASE= LUCEE_VERSION=4.5.5.015,5.3.0.86-BETA,5.2.7.62 LUCEE_SERVER=,-nginx LUCEE_VARIANTS=,-light
langauge: generic
script:
- docker pull docker.io/library/tomcat:$TOMCAT_VERSION-$TOMCAT_JAVA_VERSION$TOMCAT_BASE
- scripts/build-images.sh
services:
- docker
sudo: required
